name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons:

flutter_launcher_icons:
  android: true
  image_path: "assets/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/send-data.png
    - assets/face.jpg
    - assets/bag.png
    - assets/hoodie.png
    - assets/shirt.png
    - assets/shoe.png
    - assets/short.png
    - assets/trouser.png
    - assets/bell.png
    - assets/cart.png
    - assets/basket.png
    - assets/received.png
